package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

const COMMENT = "generate:reset"
const TEMPLATE = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by malosolnieogurchiki

{{- define "ref" }}
{{- if .IsPtr }}(*r.{{ .Name }}){{- else }}r.{{ .Name }}{{- end }}
{{- end }}

package {{ .Name }}

{{ range .StructEntries }}
func (r *{{ .Name }}) Reset() {
	{{- range .FieldEntries }}

	{{- if .IsPtr }}
		if r.{{ .Name }} != nil {
	{{- end }}

			{{- if eq .Kind "PRIME" }}
					{{ template "ref" . }} = *new({{ .PrimeType }})
			{{- else if eq .Kind "SLICE" }}
					{{ template "ref" . }} = {{ template "ref" . }}[:0]
			{{- else if eq .Kind "MAP" }}
					clear({{ template "ref" . }})
			{{- else if eq .Kind "STRUCT" }}
					if resetter, ok := any( {{ template "ref" . }} ).(interface{ Reset() }); ok {
						resetter.Reset()
					}
			{{- end }}

	{{- if .IsPtr }}
		}
	{{- end }}

	{{- end }}
}
{{ end }}
`

const (
	PRIME  = "PRIME"
	SLICE  = "SLICE"
	MAP    = "MAP"
	STRUCT = "STRUCT"
)

type PackageEntry struct {
	Name          string
	Path          string
	StructEntries []*StructEntry
}

type StructEntry struct {
	Name         string
	FieldEntries []*FieldEntry
}

type FieldEntry struct {
	Name      string
	PrimeType string
	Kind      string
	IsPtr     bool
}

type SourceFile struct {
	Path    string
	content []byte
}

func main() {
	filePaths, walkErr := getFilePaths()
	if walkErr != nil {
		log.Fatal(walkErr)
	}
	pkgEntries, pkgErr := parsePackages(filePaths)
	if pkgErr != nil {
		log.Fatal(pkgErr)
	}
	fmt.Println(pkgEntries)
	srcFiles, genErr := generateSources(pkgEntries)
	if genErr != nil {
		log.Fatal(genErr)
	}
	writeSources(srcFiles)
}

func getFilePaths() ([]string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("failed to get workdir: %v", err)
	}
	var files []string

	_ = filepath.WalkDir(wd, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if strings.HasPrefix(d.Name(), ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasPrefix(d.Name(), ".") && strings.HasSuffix(d.Name(), ".go") {
			files = append(files, path)
		}
		return nil
	})
	return files, nil
}

func parsePackages(files []string) ([]*PackageEntry, error) {
	dirPkgEntries := make(map[string]*PackageEntry)
	for _, f := range files {
		pe, err := parsePackage(f)
		if err != nil {
			log.Printf("failed to process file: %s\n", f)
			return nil, err
		}
		if len(pe.StructEntries) == 0 {
			continue
		}
		pe0, ok := dirPkgEntries[pe.Path]
		if !ok {
			dirPkgEntries[pe.Path] = pe
			continue
		}
		if pe0.Name != pe.Name {
			return nil, fmt.Errorf("packages conflict: different packages in the same dir")
		}
		pe0.StructEntries = append(pe0.StructEntries, pe.StructEntries...)
	}
	return slices.Collect(maps.Values(dirPkgEntries)), nil
}

func parsePackage(file string) (*PackageEntry, error) {
	fset := token.NewFileSet()
	f, astErr := parser.ParseFile(fset, file, nil, parser.ParseComments)
	if astErr != nil {
		return nil, astErr
	}
	structEnries, parseErr := parseFile(f)
	if parseErr != nil {
		return nil, parseErr
	}
	pe := PackageEntry{
		Name:          f.Name.Name,
		Path:          filepath.Dir(file),
		StructEntries: structEnries,
	}
	return &pe, nil
}

func parseFile(f *ast.File) ([]*StructEntry, error) {
	var structEntries []*StructEntry

	for _, d := range f.Decls {
		var gd *ast.GenDecl
		var ok bool
		if gd, ok = d.(*ast.GenDecl); !ok {
			continue
		}
		if gd.Tok != token.TYPE {
			continue
		}
		hasGroupGenerateResetComment := hasGenerateResetComment(gd.Doc)
		for _, s := range gd.Specs {
			ts := s.(*ast.TypeSpec)
			if !hasGroupGenerateResetComment && !hasGenerateResetComment(ts.Doc) {
				continue
			}
			se, err := parseStruct(ts)
			if err != nil {
				return nil, err
			}
			structEntries = append(structEntries, se)
		}
	}
	return structEntries, nil
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Trim(c.Text, "/ ") == COMMENT {
			return true
		}
	}
	return false
}

func parseStruct(n *ast.TypeSpec) (*StructEntry, error) {
	var err error

	fields := n.Type.(*ast.StructType).Fields.List
	fieldEnries := make([]*FieldEntry, len(fields))

	for i, f := range fields {
		fieldEnries[i], err = parseField(f)
		if err != nil {
			return nil, err
		}
	}
	return &StructEntry{Name: n.Name.Name, FieldEntries: fieldEnries}, nil
}

func parseField(f *ast.Field) (*FieldEntry, error) {
	var isPtr bool
	expr := f.Type
	if starExpr, ok := expr.(*ast.StarExpr); ok {
		expr = starExpr.X
		isPtr = true
	}
	kind, primeType, err := getKindPrimeType(expr)
	if err != nil {
		return nil, err
	}
	return &FieldEntry{Name: f.Names[0].Name, Kind: kind, PrimeType: primeType, IsPtr: isPtr}, nil
}

func getKindPrimeType(expr ast.Expr) (string, string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		if t.Obj == nil {
			return PRIME, t.Name, nil
		} else {
			// not really, but for simplicity
			return STRUCT, "", nil
		}
	case *ast.ArrayType:
		if t.Len == nil {
			return SLICE, "", nil
		}
	case *ast.MapType:
		return MAP, "", nil
	}
	return "", "", fmt.Errorf("undefined kind: %v", expr)
}

func generateSources(pkgEntries []*PackageEntry) ([]*SourceFile, error) {
	srcFiles := make([]*SourceFile, len(pkgEntries))

	for i, pe := range pkgEntries {
		src, err := generateSource(pe)
		if err != nil {
			return nil, err
		}
		srcFiles[i] = &SourceFile{Path: pe.Path, content: src}
	}
	return srcFiles, nil
}

func generateSource(pe *PackageEntry) ([]byte, error) {
	var buf bytes.Buffer
	templ := template.Must(template.New("reset").Parse(TEMPLATE))
	if tmplErr := templ.Execute(&buf, pe); tmplErr != nil {
		return nil, tmplErr
	}
	bufFmt, fmtErr := format.Source(buf.Bytes())
	if fmtErr != nil {
		return nil, fmtErr
	}
	return bufFmt, nil
}

func writeSources(srcFiles []*SourceFile) {
	for _, srcFile := range srcFiles {
		file := filepath.Join(srcFile.Path, "reset.gen.go")
		err := os.WriteFile(file, srcFile.content, 0644)
		if err != nil {
			log.Printf("failed to write file %s: %v\n", srcFile.Path, err)
		} else {
			log.Printf("generated: %s\n", file)
		}
	}
}
